# Generated by Django 6.0.4 on 2026-04-19 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fue_descargado', models.BooleanField(default=False)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
