# Generated by Django 6.0.4 on 2026-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='notas_adicionales',
            field=models.TextField(blank=True, help_text='Notas o condiciones especiales para este contrato', null=True),
        ),
    ]
