# Generated by Django 6.0.4 on 2026-05-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_iteminventario_options_and_more'),
        ('propiedades', '0003_propiedad_imagen'),
        ('reservas', '0003_pago_banco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='es_devolucion',
            field=models.BooleanField(default=False, help_text='True si este pago es una devolución por cancelación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cobrar_capacidad_total',
            field=models.BooleanField(default=False, help_text='En temporada alta: cobrar por capacidad máxima aunque asistan menos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='descuento_tipo',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('valor', 'Valor fijo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='descuento_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje o valor fijo del descuento', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='personas_cobradas',
            field=models.PositiveIntegerField(default=1, help_text='Personas que se cobran realmente (puede diferir en temporada alta)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_base_usado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por persona por día usado en el cálculo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio que calculó el sistema', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_modificado_manualmente',
            field=models.BooleanField(default=False, help_text='True si el usuario editó el precio final manualmente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('nit', 'NIT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, help_text='Precio final guardado (puede ser editado manualmente)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='propiedades.propiedad'),
        ),
        migrations.CreateModel(
            name='CostoDanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_danados', models.PositiveIntegerField(default=0)),
                ('items_perdidos', models.PositiveIntegerField(default=0)),
                ('items_incompletos', models.PositiveIntegerField(default=0)),
                ('total_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_a_cobrar', models.DecimalField(decimal_places=2, help_text='Puede diferir del calculado si la propietaria decide no cobrar todo', max_digits=10)),
                ('cobrado', models.BooleanField(default=False, help_text='Si el costo de daños fue incluido en un pago')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo_danio', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Costo por Daño',
                'verbose_name_plural': 'Costos por Daño',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluido_en_checkin', models.BooleanField(default=False)),
                ('estado_entrada', models.CharField(blank=True, choices=[('bien', 'En buen estado'), ('danado', 'Dañado'), ('perdido', 'Perdido'), ('incompleto', 'Incompleto')], max_length=15, null=True)),
                ('cantidad_entregada', models.PositiveIntegerField(blank=True, null=True)),
                ('notas_entrada', models.TextField(blank=True, null=True)),
                ('fecha_checkin', models.DateTimeField(blank=True, null=True)),
                ('revisado_en_checkout', models.BooleanField(default=False)),
                ('estado_salida', models.CharField(blank=True, choices=[('bien', 'En buen estado'), ('danado', 'Dañado'), ('perdido', 'Perdido'), ('incompleto', 'Incompleto')], max_length=15, null=True)),
                ('cantidad_devuelta', models.PositiveIntegerField(blank=True, null=True)),
                ('notas_salida', models.TextField(blank=True, null=True)),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True)),
                ('tiene_costo', models.BooleanField(default=False)),
                ('costo_unitario_ref', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario del ítem como referencia', max_digits=10, null=True)),
                ('costo_a_cobrar', models.DecimalField(blank=True, decimal_places=2, help_text='Monto final a cobrar, editable por el usuario', max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.iteminventario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Checklist de Reserva',
                'verbose_name_plural': 'Checklists de Reserva',
                'unique_together': {('reserva', 'item')},
            },
        ),
    ]
