# Generated by Django 6.0.4 on 2026-05-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_pago_options_pago_es_devolucion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevisionInventario',
        ),
    ]
