# Generated by Django 6.0.4 on 2026-04-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ingresos', 'Ingresos'), ('ocupacion', 'Ocupación'), ('inventario', 'Inventario')], max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('filtros', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
