# Generated by Django 6.0.4 on 2026-04-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='esta_activo',
        ),
    ]
