# Generated by Django 6.0.4 on 2026-04-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_usuariopersonalizado_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('asistente', 'Asistente'), ('empleado', 'Empleado')], default='asistente', max_length=20),
        ),
    ]
