# Generated by Django 6.0.4 on 2026-05-23 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('asistente', 'Asistente'), ('empleado', 'Empleado')], default='asistente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('nit', 'NIT')], default='cc', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PermisosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservas_ver', models.BooleanField(default=False)),
                ('reservas_crear', models.BooleanField(default=False)),
                ('reservas_editar', models.BooleanField(default=False)),
                ('reservas_eliminar', models.BooleanField(default=False)),
                ('clientes_ver', models.BooleanField(default=False)),
                ('clientes_crear', models.BooleanField(default=False)),
                ('clientes_editar', models.BooleanField(default=False)),
                ('clientes_eliminar', models.BooleanField(default=False)),
                ('propiedades_ver', models.BooleanField(default=False)),
                ('propiedades_crear', models.BooleanField(default=False)),
                ('propiedades_editar', models.BooleanField(default=False)),
                ('propiedades_eliminar', models.BooleanField(default=False)),
                ('inventario_ver', models.BooleanField(default=False)),
                ('inventario_crear', models.BooleanField(default=False)),
                ('inventario_editar', models.BooleanField(default=False)),
                ('inventario_eliminar', models.BooleanField(default=False)),
                ('reportes_ver', models.BooleanField(default=False)),
                ('reportes_crear', models.BooleanField(default=False)),
                ('reportes_editar', models.BooleanField(default=False)),
                ('reportes_eliminar', models.BooleanField(default=False)),
                ('contratos_ver', models.BooleanField(default=False)),
                ('contratos_crear', models.BooleanField(default=False)),
                ('contratos_editar', models.BooleanField(default=False)),
                ('contratos_eliminar', models.BooleanField(default=False)),
                ('usuarios_ver', models.BooleanField(default=False)),
                ('usuarios_crear', models.BooleanField(default=False)),
                ('usuarios_editar', models.BooleanField(default=False)),
                ('usuarios_eliminar', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
            },
        ),
    ]
