# Generated by Django 6.0.4 on 2026-04-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventario',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Ítem de Inventario', 'verbose_name_plural': 'Ítems de Inventario'},
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='categoria',
            field=models.CharField(choices=[('mobiliario', 'Mobiliario'), ('electrodomestico', 'Electrodoméstico'), ('ropa_cama', 'Ropa de cama'), ('utensilio_cocina', 'Utensilio de cocina'), ('decoracion', 'Decoración'), ('herramienta', 'Herramienta'), ('juegos', 'Juegos'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
