# Generated by Django 6.0.4 on 2026-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_precio_temporada_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
